export const copy = {
  productName: "ChillNote",
  nav: {
    app: "Sign in",
    pricing: "Pricing",
    privacy: "Privacy",
    terms: "Terms",
    appStore: "Get iOS App",
  },
  landing: {
    eyebrow: "Creator swipe files, from capture to reuse",
    title: "Turn creator inspiration into reusable AI-ready notes.",
    subtitle:
      "ChillNote helps creators save videos, transcribe them, break down hooks, descriptions, and transcripts, then reuse the best ideas with AI Skills.",
    primaryAction: "Sign up free",
    secondaryAction: "Sign in",
    status: "Creator workspace",
    featureTitle: "Capture the pattern, not just the link",
    featureBody:
      "Build a private swipe file where every clip, idea, transcript, and reusable prompt stays searchable and ready for your next post.",
  },
  auth: {
    brandTitle: "ChillNote",
    title: "Sign in to ChillNote",
    subtitle: "Use the same email account as your iOS app to sync notes and Pro status.",
    emailLabel: "Email",
    codeLabel: "Verification code",
    googleButton: "Sign in with Google",
    appleButton: "Sign in with Apple",
    emailButton: "Continue with email",
    backToOptions: "Back to sign-in options",
    sendCode: "Send code",
    verifyCode: "Verify and enter",
    signOut: "Sign out",
    sending: "Sending...",
    verifying: "Verifying...",
    emailPlaceholder: "you@example.com",
    codePlaceholder: "123456",
    codeSentTo: "Code sent to {email}",
    legal: "By continuing, you agree to ChillNote's Terms and Privacy Policy.",
    previewLabel: "ChillNote",
    previewTitle: "Your iOS notes, ready on the big screen",
    previewBody: "Capture on iPhone. Organize, search, and reuse your notes from the browser.",
    previewSync: "Syncs with the same ChillNote account",
    callbackLoading: "Completing sign in...",
    callbackError: "Sign-in could not be completed. Please try again.",
  },
  app: {
    title: "ChillNote",
    panels: {
      notes: {
        nav: "Notes",
        title: "Notes",
      },
      stats: {
        nav: "Stats",
        title: "Stats",
      },
      skills: {
        nav: "AI Skills",
        title: "AI Skills",
      },
      settings: {
        nav: "Settings",
        title: "Settings",
      },
    },
    sections: "App sections",
    newNote: "New note",
    save: "Save",
    saving: "Saving...",
    sync: "Sync",
    syncing: "Syncing...",
    delete: "Delete",
    emptyTitle: "No notes yet",
    emptyBody: "Create a note or record a quick brain dump to start syncing with iOS.",
    editorPlaceholder: "Type here, or record a thought and let AI tidy it.",
    searchPlaceholder: "Search notes",
    pro: "Pro",
    free: "Free",
    subscription: "Subscription",
    upgrade: "Upgrade",
    checkoutLoading: "Opening checkout...",
    recording: "Recording...",
    startRecording: "Record",
    stopRecording: "Stop",
    transcribe: "Transcribe",
    tidy: "AI tidy",
    transcribing: "Transcribing...",
    tidying: "Tidying...",
    lastSynced: "Last synced",
    neverSynced: "Not synced yet",
    noteCount: "notes",
    feedMode: "Note list mode",
    activeNotes: "Notes",
    trash: "Trash",
    restore: "Restore",
    deleteForever: "Delete forever",
    daysRemaining: "days left",
    pin: "Pin",
    unpin: "Unpin",
    pinned: "Pinned",
    tags: "Tags",
    allTags: "All notes",
    addTagPlaceholder: "Add tag",
    sourcePlaceholder: "Source URL",
    clearSource: "Clear source",
    emptyChecklistItem: "Empty task",
  },
  stats: {
    totalNotes: "Total notes",
    totalTags: "Tags",
    todayNew: "Added today",
    weekNew: "Added this week",
    dataSourceTitle: "Synced data",
    dataSourceBody:
      "Stats are calculated locally from active notes and tags returned by the existing sync endpoint. No extra backend endpoint is required for these counts yet.",
  },
  skills: {
    add: "Add",
    added: "Added",
    run: "Run skill",
    running: "Running...",
    runTitle: "Run recipe",
    savedSkills: "My skills",
    activeNote: "Current note",
    visibleNotes: "Visible notes",
    targetLanguage: "Target language",
    outputNoteHint: "The result is saved as a new note, matching the iOS recipe flow.",
  },
  settings: {
    account: "Account",
    data: "Data",
    support: "Support",
    email: "Email",
    unknownEmail: "Unknown email",
    syncStatus: "Last synced",
    voiceLanguage: "Voice language",
    autoDetect: "Auto detect",
    preferredLanguage: "Preferred",
    languageHint: "Language hint",
    autoDetectHelp: "Web recording follows the same auto-detect default as iOS.",
    privacy: "Privacy Policy",
    terms: "User Agreement",
  },
  pricing: {
    eyebrow: "Simple pricing",
    title: "Start free. Upgrade when your creator workflow needs more AI.",
    subtitle:
      "Use ChillNote for quick capture and swipe files first. Pro gives you longer recordings, more AI runs, and custom reusable skills.",
    free: {
      name: "Free",
      price: "$0",
      caption: "forever",
      cta: "Start free",
      features: [
        "Core notes and creator swipe files.",
        "Up to 1 minute per recording.",
        "Daily AI limits for transcription, tidy runs, recipes, and chat.",
      ],
    },
    monthly: {
      name: "Monthly Pro",
      price: "$12.99",
      caption: "per month",
      cta: "Choose Monthly Pro",
      features: [
        "Up to 10 minutes per recording.",
        "Unlimited AI chat about your notes.",
        "Unlimited Tidy & Polish and AI recipe runs.",
        "Create custom AI Skills.",
      ],
    },
    yearly: {
      name: "Yearly Pro",
      price: "$89.99",
      caption: "per year",
      note: "Save $65.89 compared with paying monthly all year.",
      cta: "Choose Yearly Pro",
      features: [
        "Everything in Pro, billed yearly.",
        "Up to 10 minutes per recording.",
        "Unlimited AI chat, Tidy & Polish, and AI recipe runs.",
        "Create custom AI Skills.",
      ],
    },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    signInRequired: "Please sign in first.",
    microphone: "Microphone access failed. Check browser permissions.",
    recordingUnsupported: "This browser does not support web audio recording. Try Chrome or Safari.",
    noRecording: "No recording is available yet.",
    invalidSourceURL: "Enter a valid http or https source URL.",
    emptyEmail: "Enter your email first.",
    emptyCode: "Enter the verification code.",
    emptyNote: "Write or record something before saving.",
  },
};
