export const copy = {
  productName: "ChillNote",
  nav: {
    app: "Sign in",
    pricing: "Pricing",
    privacy: "Privacy",
    terms: "Terms",
    appStore: "Get iOS App",
  },
  landing: {
    hero: {
      headlineTop: "Your Creator Notes,",
      headlineBottom: "Powered by AI",
      subtitle:
        "Capture inspiration from anywhere, let AI break it down, and turn your notes into content you actually publish.",
      primaryAction: "Get the iOS App",
      secondaryAction: "Sign in",
      orbitCaption: "Save from TikTok, Reels, YouTube & more",
    },
    capture: {
      eyebrow: "Capture",
      titlePrefix: "Capture ",
      titleHighlight: "Inspiration",
      titleSuffix: ", Your Way.",
      body:
        "Drop in a link, a voice memo, a photo, or a half-formed thought. ChillNote turns it into a clean, structured note — source, hook, transcript, and all.",
      chips: {
        link: "Link",
        voice: "Voice",
        photo: "Photo",
        media: "Media",
      },
      card: {
        sourcePlatform: "TikTok",
        sourceTitle: "4-ingredient pasta blowing up this week",
        noteTitle: "Why this pasta reel worked",
        descriptionLabel: "Description",
        description:
          "60-second TikTok by Chef Maya breaking down a 4-ingredient pasta blowing up this week.",
        authorLabel: "Author",
        author: "@chefmaya · 482K followers",
        hookLabel: "Hook",
        hook: "Why is everyone making this 4-ingredient pasta?",
        transcriptLabel: "Transcript",
        transcript:
          "Okay so the only things you need are pasta, butter, parmesan, and the one ingredient nobody is talking about. Save your pasta water, because that is where the sauce turns glossy...",
      },
    },
    share: {
      eyebrow: "Share Extension",
      titlePrefix: "Share From ",
      titleHighlight: "Anywhere",
      titleSuffix: ".",
      body:
        "Save TikToks, Reels & YouTube clips straight into ChillNote — without leaving the app you're in. Tap Share, pick ChillNote, done.",
      steps: [
        "Find something worth saving",
        "Tap the system Share button",
        "Send it straight to ChillNote",
      ],
    },
    skills: {
      eyebrow: "AI Skills",
      titlePrefix: "Turn Notes Into ",
      titleHighlight: "Content.",
      body:
        "Run reusable AI Skills against your notes — generate hooks, write caption packs, humanize a draft, or repurpose one idea across every platform.",
      previewLabel: "Skill Preview",
      buildYourOwn: "Build your own AI Skills",
      tabs: {
        hooks: "Hooks",
        caption: "Caption Pack",
        humanizer: "Humanizer",
        repurpose: "Repurpose",
      },
      demos: {
        hooks: [
          { label: "Direct", text: "Stop losing good ideas inside messy notes." },
          { label: "Question", text: "What if your next post is already sitting in your notes?" },
          { label: "Contrast", text: "I did not need more ideas. I needed a way to reuse the ones I had." },
        ],
        caption: [
          { label: "TikTok", text: "Save this if your notes keep turning into drafts you never post." },
          { label: "YouTube", text: "Turn messy creator notes into posts you can actually ship." },
          { label: "Reels", text: "A faster way to turn saved ideas into captions you can use." },
        ],
        humanizer: [
          { label: "Before", text: "It is not just a note-taking app. It is a comprehensive system designed to enhance your creative workflow." },
          { label: "After", text: "It is not just for taking notes. It helps you keep ideas moving when you are making content." },
        ],
        repurpose: [
          { label: "X Thread", text: "1/ The best ideas are already in your notes. Turn one long draft into a thread people can scan." },
          { label: "LinkedIn", text: "A long note becomes a clean professional post with the core insight up front." },
          { label: "Newsletter", text: "This week: how to turn saved inspiration into a repeatable publishing flow." },
        ],
      },
    },
    final: {
      titlePrefix: "Stop losing good ideas inside ",
      titleHighlight: "messy notes",
      titleSuffix: ".",
      body:
        "Capture on iPhone, organize and reuse from the web. The same notes, the same AI Skills, everywhere you create.",
      primaryAction: "Get the iOS App",
      secondaryAction: "Sign in",
    },
  },
  auth: {
    brandTitle: "ChillNote",
    title: "Welcome back",
    subtitle: "Sign in to continue",
    brandHeadline: "Capture on iPhone.\nContinue on the web.",
    brandFeatures: [
      "Notes synced across devices",
      "Reusable AI Skills",
      "Quick Capture inbox",
    ],
    dividerLabel: "or",
    backToHome: "Back to home",
    emailLabel: "Email",
    codeLabel: "Verification code",
    googleButton: "Sign in with Google",
    appleButton: "Sign in with Apple",
    emailButton: "Continue with email",
    backToOptions: "Back to sign-in options",
    sendCode: "Send code",
    verifyCode: "Verify and enter",
    signOut: "Sign out",
    sending: "Sending...",
    verifying: "Verifying...",
    emailPlaceholder: "you@example.com",
    codePlaceholder: "123456",
    codeSentTo: "Code sent to {email}",
    legal: "By continuing, you agree to ChillNote's Terms and Privacy Policy.",
    previewLabel: "ChillNote",
    previewTitle: "Your iOS notes, ready on the big screen",
    previewBody: "Capture on iPhone. Organize, search, and reuse your notes from the browser.",
    previewSync: "Syncs with the same ChillNote account",
    callbackLoading: "Completing sign in...",
    callbackError: "Sign-in could not be completed. Please try again.",
  },
  app: {
    title: "ChillNote",
    panels: {
      notes: {
        nav: "Notes",
        title: "Notes",
      },
      skills: {
        nav: "AI Skills",
        title: "AI Skills",
      },
      settings: {
        nav: "Settings",
        title: "Settings",
      },
    },
    sections: "App sections",
    sectionFilter: "Sections",
    sectionInbox: "Inbox",
    sectionDrafts: "Drafts",
    sectionPublished: "Published",
    moveSection: "Move to section",
    newNote: "New note",
    captureHeading: "Capture an idea",
    captureWrite: "Write",
    captureRecord: "Record",
    captureRecording: "Recording…",
    captureTranscribing: "Transcribing…",
    capturePasteLink: "Paste link",
    captureLinkPlaceholder: "Paste a TikTok, YouTube, or web link",
    captureLinkAdd: "Save",
    showMoreTags: "More",
    showFewerTags: "Less",
    synced: "Synced",
    source: "Source link",
    back: "Back",
    save: "Save",
    saving: "Saving...",
    saved: "Saved",
    sync: "Sync",
    syncing: "Syncing...",
    delete: "Delete",
    emptyTitle: "No notes yet",
    emptyBody: "Create a note or record a quick brain dump to start syncing with iOS.",
    editorPlaceholder: "Type here, or record a thought.",
    searchPlaceholder: "Search notes",
    pro: "Pro",
    free: "Free",
    subscription: "Subscription",
    upgrade: "Upgrade",
    checkoutLoading: "Opening checkout...",
    recording: "Recording...",
    startRecording: "Record",
    stopRecording: "Stop",
    transcribe: "Transcribe",
    transcribing: "Transcribing...",
    lastSynced: "Last synced",
    neverSynced: "Not synced yet",
    noteCount: "notes",
    feedMode: "Note list mode",
    activeNotes: "Notes",
    trash: "Trash",
    restore: "Restore",
    deleteForever: "Delete forever",
    daysRemaining: "days left",
    pin: "Pin",
    unpin: "Unpin",
    pinned: "Pinned",
    tags: "Tags",
    allTags: "All notes",
    addTagPlaceholder: "Add tag",
    sourcePlaceholder: "Source URL",
    clearSource: "Clear source",
    emptyChecklistItem: "Empty task",
  },
  skills: {
    add: "Add",
    added: "Added",
    remove: "Remove",
    library: "Library",
    mySkills: "My Skills",
    emptyTitle: "No Skills Yet",
    emptyBody: "Add Skills from the library. Creating your own custom actions is available for paid members.",
    configure: "Configure",
    run: "Run skill",
    running: "Running...",
    runTitle: "Run recipe",
    savedSkills: "My skills",
    activeNote: "Current note",
    visibleNotes: "Visible notes",
    targetLanguage: "Target language",
    outputNoteHint: "The result is saved as a new note, matching the iOS recipe flow.",
  },
  editor: {
    toolbarLabel: "Editor tools",
    bold: "Bold",
    todo: "Add todo",
    undo: "Undo",
    aiSkills: "AI Skills",
    aiSkillsTitle: "Run AI Skill",
    chooseSkill: "Choose skill",
    applySkill: "Apply to note",
    aiSkillsHint: "The result will replace the current note content.",
    starSkill: "Save to My Skills",
    unstarSkill: "Saved to My Skills",
  },
  captionPack: {
    settingsTitle: "Caption Pack Settings",
    platforms: "Platforms",
    goal: "Goal",
    tone: "Tone",
    outputStyle: "Output Style",
    done: "Done",
    platformTikTok: "TikTok",
    platformYoutubeShorts: "YouTube Shorts",
    platformInstagramReels: "Instagram Reels",
    goals: {
      startDiscussion: "Start discussion",
      getSaves: "Get saves",
      getShares: "Get shares",
      driveFollows: "Drive follows",
    },
    tones: {
      casualUseful: "Casual + useful",
      educational: "Educational",
      bold: "Bold",
      storyDriven: "Story-driven",
      creatorVoice: "Creator voice",
    },
    outputStyles: {
      concise: "Concise",
      balanced: "Balanced",
      detailed: "Detailed",
    },
  },
  settings: {
    account: "Account",
    data: "Data",
    support: "Support",
    email: "Email",
    unknownEmail: "Unknown email",
    syncStatus: "Last synced",
    voiceLanguage: "Voice language",
    autoDetect: "Auto detect",
    preferredLanguage: "Preferred",
    languageHint: "Language hint",
    autoDetectHelp: "Web recording follows the same auto-detect default as iOS.",
    privacy: "Privacy Policy",
    terms: "User Agreement",
  },
  pricing: {
    eyebrow: "Simple pricing",
    title: "Start free. Upgrade when your creator workflow needs more AI.",
    subtitle:
      "Use ChillNote for quick capture and AI creator notes first. Pro gives you longer recordings, more AI runs, and custom reusable skills.",
    free: {
      name: "Free",
      price: "$0",
      caption: "forever",
      cta: "Start free",
      features: [
        "Core notes and your AI creator notes workspace.",
        "Up to 1 minute per recording.",
        "Daily AI limits for transcription, recipes, and chat.",
      ],
    },
    monthly: {
      name: "Monthly Pro",
      price: "$12.99",
      caption: "per month",
      cta: "Choose Monthly Pro",
      features: [
        "Up to 10 minutes per recording.",
        "Unlimited AI chat about your notes.",
        "Unlimited AI recipe runs.",
        "Create custom AI Skills.",
      ],
    },
    yearly: {
      name: "Yearly Pro",
      price: "$89.99",
      caption: "per year",
      note: "Save $65.89 compared with paying monthly all year.",
      cta: "Choose Yearly Pro",
      features: [
        "Everything in Pro, billed yearly.",
        "Up to 10 minutes per recording.",
        "Unlimited AI chat and AI recipe runs.",
        "Create custom AI Skills.",
      ],
    },
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    signInRequired: "Please sign in first.",
    microphone: "Microphone access failed. Check browser permissions.",
    recordingUnsupported: "This browser does not support web audio recording. Try Chrome or Safari.",
    noRecording: "No recording is available yet.",
    invalidSourceURL: "Enter a valid http or https source URL.",
    emptyEmail: "Enter your email first.",
    emptyCode: "Enter the verification code.",
    emptyNote: "Write or record something before saving.",
  },
};
